// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5DCifBwXrjzSHHvPjULgM3VCzi5hPCc',
    appId: '1:243479158021:web:c5c36db1966df8998fab6c',
    messagingSenderId: '243479158021',
    projectId: 'analytics-example-11f4a',
    authDomain: 'analytics-example-11f4a.firebaseapp.com',
    storageBucket: 'analytics-example-11f4a.appspot.com',
    measurementId: 'G-30C0TS7RZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YlSeoyYtaxvEmc1Km3M5f__51LYIRrQ',
    appId: '1:243479158021:android:7708a3918fbd7dc48fab6c',
    messagingSenderId: '243479158021',
    projectId: 'analytics-example-11f4a',
    storageBucket: 'analytics-example-11f4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaN1J1bJGMqwfaVECGSc_axxZA8FdBBk4',
    appId: '1:243479158021:ios:73519e68d3f6045a8fab6c',
    messagingSenderId: '243479158021',
    projectId: 'analytics-example-11f4a',
    storageBucket: 'analytics-example-11f4a.appspot.com',
    iosClientId: '243479158021-cdot5qgbobjjgvhibg88n6a7herthvb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.analyticsExample',
  );
}
